controllers:
  # Publish all joint states -----------------------------------
  joint_state:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  # Position Controllers --------------------------------------
